# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('url', models.URLField(max_length=500)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Website')),
            ],
        ),
    ]
