# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-13 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article'),
        ('news', '0002_website_language'),
    ]

    operations = [
    ]
