# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20171013_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='website',
            name='image_url',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
