# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20171119_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlerating',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articlerating',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
