# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20171120_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(null=True),
        ),
    ]
