# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20171127_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='website',
            name='language',
            field=models.CharField(db_index=True, default='', max_length=15),
        ),
    ]
