FROM python:3.6.0-alpine
MAINTAINER TCCPoli "tccpoli2017@gmail.com"

COPY setup.py /usr/src/app/setup.py
WORKDIR /usr/src/app

RUN apk --no-cache add musl-dev linux-headers g++ \
    && python setup.py egg_info \
    && python setup.py develop \
    && apk del musl-dev linux-headers g++

ENV DEPLOYMENT_ENVIRONMENT=dev

CMD ["gunicorn", "--paste", "development.ini"]
